inputs_def:
  - handle: data
    description: "%table-data-to-sample-from%"
    json_schema:
      type: array
      items:
        type: object
    nullable: false

  - handle: method
    description: "%sampling-method%"
    json_schema:
      type: string
      enum:
        - random
        - stratified
        - systematic
        - head
        - tail
    nullable: false

  - handle: size
    description: "%sample-size-count-if-1-proportion-if-0-size-1%"
    json_schema:
      type: number
    nullable: false

  - handle: params
    description: "%method-specific-parameters%"
    json_schema:
      type: object
      properties:
        stratifyColumn:
          type: string
        seed:
          type: integer
        replacement:
          type: boolean
    value:
    nullable: true

outputs_def:
  - handle: sample
    description: "%sampled-data%"
    json_schema:
      type: array
      items:
        type: object

  - handle: indices
    description: "%original-data-indices-of-sampled-rows%"
    json_schema:
      type: array
      items:
        type: integer

  - handle: sampleSize
    description: "%actual-number-of-rows-in-sample%"
    json_schema:
      type: integer

  - handle: originalSize
    description: "%original-data-size%"
    json_schema:
      type: integer

  - handle: method
    description: "%sampling-method-used%"
    json_schema:
      type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%table-sampler%"
icon: ":carbon:filter-edit:"
description: "%sample-data-using-various-methods-random-stratified-systematic-h%"
