inputs_def:
  - handle: data
    description: "%table-data-to-split%"
    json_schema:
      type: array
      items:
        type: object
    nullable: false

  - handle: method
    description: "%splitting-method%"
    json_schema:
      type: string
      enum:
        - ratio
        - condition
        - chunks
        - stratified
    nullable: false

  - handle: params
    description: "%splitting-parameters-auto-configured-based-on-method%"
    json_schema:
      type: object
      properties:
        ratios:
          type: array
          items:
            type: number
        names:
          type: array
          items:
            type: string
        shuffle:
          type: boolean
        seed:
          type: integer
        conditions:
          type: array
          items:
            type: object
        chunkSize:
          type: integer
        stratifyColumn:
          type: string
    value: null
    nullable: true

outputs_def:
  - handle: splits
    description: "%array-of-split-datasets%"
    json_schema:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          data:
            type: array
            items:
              type: object
          size:
            type: integer
          percentage:
            type: number

  - handle: method
    description: "%splitting-method-used%"
    json_schema:
      type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%table-splitter%"
icon: ":carbon:split:"
description: "%split-table-data-by-ratio-conditions-chunks-or-stratified-sampli%"
